// lib/mockHotels.ts
// Temporary mock data. Replace with a real fetch to your hotel API/DB —
// the shape matches the `Hotel` type 1:1 so swapping later is a no-op for the UI.

import { Hotel } from "@/types/hotel";

const img = (seed: string) => `https://picsum.photos/seed/${seed}/800/600`;

export const mockHotels: Hotel[] = [
  {
    _id: "h1",
    name: "Espinas Palace Hotel",
    description:
      "A landmark 5-star hotel with panoramic city views, multiple restaurants, and a rooftop pool.",
    location: { city: "Tehran", address: "Africa Blvd, Tehran", zipCode: "1968653315" },
    starRating: 5,
    guestRating: 4.6,
    reviewCount: 842,
    propertyType: "hotel",
    amenities: ["Free WiFi", "Breakfast included", "Parking", "Pool", "Spa", "Gym", "Air Conditioning"],
    images: [img("espinas1"), img("espinas2")],
    checkInTime: "14:00",
    checkOutTime: "12:00",
    totalRooms: 3,
    availableRooms: 2,
    minPrice: 4_200_000,
    maxPrice: 9_800_000,
    rooms: [
      { roomNumber: "101", roomType: "double", capacity: 2, price: 4_200_000, amenities: ["Free WiFi", "Air Conditioning"], images: [img("espinas-r1")], description: "Double room with city view", isAvailable: true },
      { roomNumber: "202", roomType: "suite", capacity: 4, price: 7_500_000, amenities: ["Free WiFi", "Spa access"], images: [img("espinas-r2")], description: "Executive suite", isAvailable: true },
      { roomNumber: "303", roomType: "deluxe", capacity: 3, price: 9_800_000, amenities: ["Free WiFi", "Breakfast included"], images: [img("espinas-r3")], description: "Deluxe room with balcony", isAvailable: false },
    ],
  },
  {
    _id: "h2",
    name: "Shiraz Grand Hotel",
    description: "Classic hospitality near Shiraz's historical gardens, popular with families.",
    location: { city: "Shiraz", address: "Zand St, Shiraz", zipCode: "7134846911" },
    starRating: 4,
    guestRating: 4.2,
    reviewCount: 356,
    propertyType: "hotel",
    amenities: ["Free WiFi", "Breakfast included", "Parking", "Air Conditioning", "Pet-friendly"],
    images: [img("shiraz1"), img("shiraz2")],
    checkInTime: "13:00",
    checkOutTime: "12:00",
    totalRooms: 2,
    availableRooms: 2,
    minPrice: 2_100_000,
    maxPrice: 3_600_000,
    rooms: [
      { roomNumber: "10", roomType: "single", capacity: 1, price: 2_100_000, amenities: ["Free WiFi"], images: [img("shiraz-r1")], description: "Cozy single room", isAvailable: true },
      { roomNumber: "11", roomType: "double", capacity: 2, price: 3_600_000, amenities: ["Free WiFi", "Breakfast included"], images: [img("shiraz-r2")], description: "Garden-view double", isAvailable: true },
    ],
  },
  {
    _id: "h3",
    name: "Kish Sunset Resort",
    description: "Beachfront resort on Kish Island with water sports and an all-day buffet.",
    location: { city: "Kish", address: "Coastal Rd, Kish Island", zipCode: "7941653411" },
    starRating: 5,
    guestRating: 4.7,
    reviewCount: 1204,
    propertyType: "resort",
    amenities: ["Free WiFi", "Breakfast included", "Pool", "Spa", "Gym", "Air Conditioning", "Pet-friendly"],
    images: [img("kish1"), img("kish2")],
    checkInTime: "15:00",
    checkOutTime: "12:00",
    totalRooms: 3,
    availableRooms: 1,
    minPrice: 6_000_000,
    maxPrice: 14_500_000,
    rooms: [
      { roomNumber: "A1", roomType: "double", capacity: 2, price: 6_000_000, amenities: ["Pool access"], images: [img("kish-r1")], description: "Sea-view double", isAvailable: true },
      { roomNumber: "A2", roomType: "suite", capacity: 4, price: 10_200_000, amenities: ["Pool access", "Spa access"], images: [img("kish-r2")], description: "Family suite", isAvailable: false },
      { roomNumber: "A3", roomType: "deluxe", capacity: 2, price: 14_500_000, amenities: ["Private terrace"], images: [img("kish-r3")], description: "Deluxe beachfront room", isAvailable: false },
    ],
  },
  {
    _id: "h4",
    name: "Naghsh-e Jahan Boutique",
    description: "A restored traditional house turned boutique hotel steps from Naqsh-e Jahan Square.",
    location: { city: "Isfahan", address: "Chaharbagh Ave, Isfahan", zipCode: "8174734411" },
    starRating: 4,
    guestRating: 4.8,
    reviewCount: 512,
    propertyType: "hotel",
    amenities: ["Free WiFi", "Breakfast included", "Air Conditioning"],
    images: [img("isfahan1"), img("isfahan2")],
    checkInTime: "14:00",
    checkOutTime: "11:00",
    totalRooms: 2,
    availableRooms: 2,
    minPrice: 3_300_000,
    maxPrice: 5_100_000,
    rooms: [
      { roomNumber: "1", roomType: "double", capacity: 2, price: 3_300_000, amenities: ["Free WiFi"], images: [img("isfahan-r1")], description: "Courtyard-facing double", isAvailable: true },
      { roomNumber: "2", roomType: "suite", capacity: 3, price: 5_100_000, amenities: ["Free WiFi", "Breakfast included"], images: [img("isfahan-r2")], description: "Traditional-style suite", isAvailable: true },
    ],
  },
  {
    _id: "h5",
    name: "Tabriz Central Inn",
    description: "Budget-friendly hostel near the Grand Bazaar, popular with backpackers.",
    location: { city: "Tabriz", address: "Bazaar St, Tabriz", zipCode: "5155664411" },
    starRating: 2,
    guestRating: 3.6,
    reviewCount: 128,
    propertyType: "hostel",
    amenities: ["Free WiFi", "Parking"],
    images: [img("tabriz1"), img("tabriz2")],
    checkInTime: "12:00",
    checkOutTime: "10:00",
    totalRooms: 2,
    availableRooms: 2,
    minPrice: 900_000,
    maxPrice: 1_600_000,
    rooms: [
      { roomNumber: "S1", roomType: "single", capacity: 1, price: 900_000, amenities: ["Free WiFi"], images: [img("tabriz-r1")], description: "Basic single room", isAvailable: true },
      { roomNumber: "S2", roomType: "double", capacity: 2, price: 1_600_000, amenities: ["Free WiFi"], images: [img("tabriz-r2")], description: "Shared double room", isAvailable: true },
    ],
  },
  {
    _id: "h6",
    name: "Yazd Desert Villa",
    description: "A private villa on the edge of the desert with its own courtyard pool.",
    location: { city: "Yazd", address: "Fahadan District, Yazd", zipCode: "8916643311" },
    starRating: 4,
    guestRating: 4.4,
    reviewCount: 96,
    propertyType: "villa",
    amenities: ["Free WiFi", "Pool", "Parking", "Air Conditioning", "Pet-friendly"],
    images: [img("yazd1"), img("yazd2")],
    checkInTime: "14:00",
    checkOutTime: "12:00",
    totalRooms: 1,
    availableRooms: 1,
    minPrice: 5_500_000,
    maxPrice: 5_500_000,
    rooms: [
      { roomNumber: "V1", roomType: "deluxe", capacity: 6, price: 5_500_000, amenities: ["Pool access", "Private courtyard"], images: [img("yazd-r1")], description: "Whole villa, sleeps 6", isAvailable: true },
    ],
  },
  {
    _id: "h7",
    name: "Darband Apartments",
    description: "Modern serviced apartments at the foot of the Alborz mountains in north Tehran.",
    location: { city: "Tehran", address: "Darband St, Tehran", zipCode: "1963643311" },
    starRating: 3,
    guestRating: 4.0,
    reviewCount: 214,
    propertyType: "apartment",
    amenities: ["Free WiFi", "Parking", "Air Conditioning", "Gym"],
    images: [img("darband1"), img("darband2")],
    checkInTime: "14:00",
    checkOutTime: "12:00",
    totalRooms: 2,
    availableRooms: 0,
    minPrice: 2_800_000,
    maxPrice: 4_400_000,
    rooms: [
      { roomNumber: "D1", roomType: "double", capacity: 2, price: 2_800_000, amenities: ["Kitchenette"], images: [img("darband-r1")], description: "One-bedroom apartment", isAvailable: false },
      { roomNumber: "D2", roomType: "suite", capacity: 4, price: 4_400_000, amenities: ["Kitchenette", "Balcony"], images: [img("darband-r2")], description: "Two-bedroom apartment", isAvailable: false },
    ],
  },
  {
    _id: "h8",
    name: "Caspian Shore Resort",
    description: "Family resort on the Caspian coast with indoor and outdoor pools.",
    location: { city: "Ramsar", address: "Coastal Blvd, Ramsar", zipCode: "4691843311" },
    starRating: 5,
    guestRating: 4.5,
    reviewCount: 673,
    propertyType: "resort",
    amenities: ["Free WiFi", "Breakfast included", "Pool", "Gym", "Air Conditioning", "Parking"],
    images: [img("ramsar1"), img("ramsar2")],
    checkInTime: "15:00",
    checkOutTime: "12:00",
    totalRooms: 2,
    availableRooms: 2,
    minPrice: 5_200_000,
    maxPrice: 8_900_000,
    rooms: [
      { roomNumber: "R1", roomType: "double", capacity: 2, price: 5_200_000, amenities: ["Sea view"], images: [img("ramsar-r1")], description: "Sea-view double", isAvailable: true },
      { roomNumber: "R2", roomType: "suite", capacity: 4, price: 8_900_000, amenities: ["Sea view", "Balcony"], images: [img("ramsar-r2")], description: "Family suite", isAvailable: true },
    ],
  },
];
