// TEMPORARY — for previewing the hotel booking UI only.
// Delete this file once getHotelById in page.tsx is wired to the real API.

import { HotelDetail } from "@/types/hotel-booking";

export const mockHotelDetail: HotelDetail = {
  _id: "mock-hotel-1",
  name: "Luxury Resort Hotel",
  description:
    "Experience luxury and comfort at our award-winning resort hotel with world-class amenities.",
  location: {
    city: "Tehran",
    address: "123 Valiasr Street",
    zipCode: "1919191",
  },
  starRating: 5,
  guestRating: 4.8,
  reviewCount: 342,
  propertyType: "resort",
  rooms: [
    // Deluxe rooms
    {
      roomNumber: "D101",
      roomType: "deluxe",
      capacity: 2,
      price: 450,
      amenities: ["WiFi", "AC", "TV", "Hot tub"],
      images: ["/images/room-placeholder.jpg"],
      description: "Spacious deluxe room with premium amenities",
      isAvailable: true,
    },
    {
      roomNumber: "D102",
      roomType: "deluxe",
      capacity: 2,
      price: 450,
      amenities: ["WiFi", "AC", "TV", "Hot tub"],
      images: ["/images/room-placeholder.jpg"],
      description: "Spacious deluxe room with premium amenities",
      isAvailable: false,
    },
    {
      roomNumber: "D103",
      roomType: "deluxe",
      capacity: 2,
      price: 450,
      amenities: ["WiFi", "AC", "TV", "Hot tub"],
      images: ["/images/room-placeholder.jpg"],
      description: "Spacious deluxe room with premium amenities",
      isAvailable: true,
    },
    // Suites
    {
      roomNumber: "S201",
      roomType: "suite",
      capacity: 4,
      price: 350,
      amenities: ["WiFi", "AC", "TV", "Kitchen"],
      images: ["/images/room-placeholder.jpg"],
      description: "Comfortable suite with separate living area",
      isAvailable: true,
    },
    {
      roomNumber: "S202",
      roomType: "suite",
      capacity: 4,
      price: 350,
      amenities: ["WiFi", "AC", "TV", "Kitchen"],
      images: ["/images/room-placeholder.jpg"],
      description: "Comfortable suite with separate living area",
      isAvailable: true,
    },
    // Double rooms
    {
      roomNumber: "DB301",
      roomType: "double",
      capacity: 2,
      price: 220,
      amenities: ["WiFi", "AC", "TV"],
      images: ["/images/room-placeholder.jpg"],
      description: "Cozy double room for two guests",
      isAvailable: true,
    },
    {
      roomNumber: "DB302",
      roomType: "double",
      capacity: 2,
      price: 220,
      amenities: ["WiFi", "AC", "TV"],
      images: ["/images/room-placeholder.jpg"],
      description: "Cozy double room for two guests",
      isAvailable: false,
    },
    {
      roomNumber: "DB303",
      roomType: "double",
      capacity: 2,
      price: 220,
      amenities: ["WiFi", "AC", "TV"],
      images: ["/images/room-placeholder.jpg"],
      description: "Cozy double room for two guests",
      isAvailable: true,
    },
    // Single rooms
    {
      roomNumber: "SG401",
      roomType: "single",
      capacity: 1,
      price: 120,
      amenities: ["WiFi", "AC"],
      images: ["/images/room-placeholder.jpg"],
      description: "Compact single room",
      isAvailable: true,
    },
    {
      roomNumber: "SG402",
      roomType: "single",
      capacity: 1,
      price: 120,
      amenities: ["WiFi", "AC"],
      images: ["/images/room-placeholder.jpg"],
      description: "Compact single room",
      isAvailable: true,
    },
  ],
  amenities: [
    "Pool",
    "Gym",
    "Spa",
    "Restaurant",
    "WiFi",
    "Parking",
    "Concierge",
  ],
  images: ["/images/hotel-summary-placeholder.jpg"],
  checkInTime: "15:00",
  checkOutTime: "11:00",
  totalRooms: 10,
  availableRooms: 7,
  minPrice: 120,
  maxPrice: 450,
};
